### ISSUE TITLE
L.heatLayer is not a function

### ISSUE THREAD

**Issue by sgofferj** [alexandrainst/alexandra-trackmap-panel#5]
I had problems with getting InfluxDB data to display (s. #2 ). After getting it to work, it suddenly stopped working with Grafana 6.4.1 and with the update to 6.4.2, I get the following error:

```
Panel data error: TypeError: "L.heatLayer is not a function"            metrics_panel_ctrl.ts:202:6
    value module.js:10
    value module.js:10
    emit index.js:129
    emit emitter.ts:11
    handleQueryResult sdk.ts:1
    next metrics_panel_ctrl.ts:82
    RxJS 8
        __tryOrUnsub
        next
        _next
        next
        _next
        next
        next
        nextInfiniteTimeWindow
    next PanelModel.ts:5
    RxJS 19
        __tryOrUnsub
        next
        _next
        next
        notifyNext
        _next
        next
        _next
        next
        next
        _next
        next
        _next
        next
        _next
        next
        _next
        next
        o
    Angular 6
        f
        f
        $digest
        evalAsync
        p
        n
```

Just updated to 6.4.3 and the error is still there:
```
Panel data error: TypeError: "L.heatLayer is not a function"           metrics_panel_ctrl.ts:202:6
    value module.js:10
    value module.js:10
    emit index.js:129
    emit emitter.ts:11
    handleQueryResult sdk.ts:1
    next metrics_panel_ctrl.ts:82
    RxJS 8
        __tryOrUnsub
        next
        _next
        next
        _next
        next
        next
        nextInfiniteTimeWindow
    next PanelModel.ts:5
    RxJS 19
        __tryOrUnsub
        next
        _next
        next
        notifyNext
        _next
        next
        _next
        next
        next
        _next
        next
        _next
        next
        _next
        next
        _next
        next
        o
    Angular 7
        f
        f
        $digest
        $apply
        r
        p
        n
```

**Comment by Alkarex** [comment]
Hello @sgofferj , would you have the possibility of testing this candidate fix? https://github.com/alexandrainst/alexandra-trackmap-panel/pull/6

**Comment by sgofferj** [comment]
I'll try to test it this week.

**Comment by Alkarex** [comment]
@sgofferj Thanks. Looking forward to your feedback
